### ISSUE TITLE
Duplicated edges with the same iri

### ISSUE THREAD

**Issue by cbobed** [Rothamsted/rdf2neo#3]
I'm getting duplicated triples coming from different queries: I've double checked that it is exactly the same iri for both triples, but I get the edges duplicated in the property graph (the inner IDs are different). 

I've got a test with classes Person and Location (among others). Person has a property with range Location, and I've put it in the Person_rel_type sparql query. I've done the same for Location (the domain of hasLocation is owl:Thing), but I got one different edge for each query execution in spite of having exactly the same iri (I've used an artificial "namespace" built concatenating the URI of the property + "/" + the MD5 hash of the triple). Is it normal? I thought I was safe from duplications using the BIND clause you use for the iri generation. 

Besides, although I'm pretty sure it is commented in the paper, what does it happen exactly to non-seen nodes? are they built on-the-fly?

**Comment by marco-brandizi** [comment]
You, as the writer of the SPARQL IRI selectors, must take care that the queries don't return duplicated URIs. At least for now, we don't check for duplicates (would make things too slow) and neither Neo4J does it (the latter identifies nodes/relations based only on the internal 'id' attribute, one can create identical nodes or relations without any complain from Neo4J). So, you have to use DISTINCT or use exclusion clauses, for instance, we have to do so [here](https://github.com/Rothamsted/ondex-knet-builder/blob/master/modules/neo4j-export/src/main/assembly/resources/ondex_config/concept_rel_types.sparql) (see the MINUS clause).

If I get it well, the Person/Location case has a similar problem.

Not sure what you mean with 'non-seen' nodes. Relation-related queries must return node URIs that were returned by node-related queries, so that nodes are already created in Neo4J when the converter comes to the relations.

**Comment by cbobed** [comment]
Ok, now I see. My fault ... I assumed that the rel_types queries in the examples were bound to the nodes generated in the node IRI generations (the first stage) and I had different overlapping relationships queries "associated to different classes". I had one SPARQL query retrieving locations for People thinking that it was executed once per People IRI, but in the end the way of thinking should be exactly the same as for nodes ... as it matches the triples of the relationships regardless the types/iris of the subjects and objects, am I right with this vision? 

If so, retaking the non-seen nodes (i.e, resources in the RDF graph that haven't had been asigned a node), how are they handled? Let's assume that we have three classes A,B,C, but I only want to include in the property graph the instances for A and C. There is as well one property p that is relating the three of them (it's defined with very broad domain and ranges). I would have one configItem for A, one configItem for B, and I could have another configItem for p. In the sparqlQuery for p (following the examples), I could go for a (?fromIri ?type ?toIri) pattern and it would match instances of C which were not generated. Must I control this kind of situations from the SPARQL query? 

Thank you very much for all your comments :)

**Comment by marco-brandizi** [comment]
the relation type selector is expected to return this:

```sql
SELECT ?iri ?type ?fromIri ?toIri
...
```

?iri identifies the relation (and you must ensure they're not duplicated). ?fromIri, ?toIri must point to resources that were already created as Neo4j nodes (ie, the respective queries must select them too). Relations are created via Cypher with commands like:

```
MATCH (s:Resource{iri:$siri}), (d:Resource{iri:$diri})
CREATE (s)-[:$type]-(d)
```
Where all `$xxx` variables are placeholders, instantiated from the values coming from the relation type selector. `Resource` is a default node label, which is always added to every node, in addition to your own labels, defined via SPARQL labels selector. The default label is needed precisely to have something to refer to existing nodes, independently on their more specific labels (we use `Resource` for this, but it can be changed via config file, though I doubt that will ever be needed).

So, as you can see, nodes are referred by means of URIs, no matter what their `rdf:type` is (indeed they might even have no RDF class at all, you might select them with criteria like: `?iri myns:goesToNeo4j true`).

As for your case, if you don't want B instances on Neo4j, you've to exclude them from both the nodes selection and the relations selection. For instance, if you expect that `?x p ?y` might contain instances of B as ?y, you need to write something like:

```sql
SELECT ?iri ?type ?fromIri ?toIri
WHERE 
{
  BIND ( myns:p AS ?type ) # or, in this case, even 'p' AS ?type

  ?fromIri myns:p ?toIri
  
  MINUS  { ?toIri rdf:type myns:B }
  
  # An alternative would be working by inclusion, ie, instead of MINUS, add the BGP:
  # { ?toIri rdf:type myns:C }
  #   UNION { ?toIri rdf:type myns:C } # assuming inference/transitive closure is off
  
  # Build a fictitius ?iri using ?fromIri, ?toIri, ?type
  ...
}
```

This will work, assuming you didn't select instances of B in the node selectors. So, in conclusion, yes, you must keep node and relation selectors coherent with one each other. 

A related thing coming in my mind is that, if dealing with these particular cases is difficult (ie, forces you to write much tricky/slow SPARQL), it might be useful to first transform your RDF into a simpler model, one closer to the property graph model. For instance, using CONSTRUCT or DELETE/INSERT (over a writeable TDB), you could define a graph like this: 

```turtle
@prefix pg: <....>

?node a pg:Node;
  pg:prop [ a pg:Prop; pg:key 'firstName'; pg:value 'John' ]

?rel a pg:Rel;
  pg:from ?s;
  pg:to ?s;
  pg:prop [...]    
``` 

Transformations like this might be simpler to write, cause they manage issues like duplicates automatically (and indeed that's one of the strengths of triple stores, compared to property graphs). Once you have a graph like the above, writing queries for our rdf2neo would be pretty straightforward. Indeed, there are [people working on a standard vocabulary](https://www.w3.org/Data/events/data-ws-2019/) to represent PGs in RDF, and I plan to support such a vocabulary in rdf2neo, once it is available.
 
Hope I got you right and this helps.

**Comment by cbobed** [comment]
Indeed, this was exactly what I had in mind :) 

Thank you very much! 

If you see that we could collaborate anyhow, don't hesitate to contact me :) In the meantime, I'll prepare both pull requests (rdfutils and rdf2neo).

**Comment by marco-brandizi** [comment]
I've added a reference to the clarifications given in this issue and now I'm closing it.
