### ISSUE TITLE
Problem with maven dependencies

### ISSUE THREAD

**Issue by cbobed** [Rothamsted/rdf2neo#6]
Hi, 

when building the project, maven cannot retrieve some of the dependencies. It seems that the server is not being able to serve some of the .jar files: 

`[INFO] Downloading from : https://knetminer.org/artifactory/repository/maven-public/uk/ac/ebi/jutils/9.0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata uk.ac.ebi:jutils:9.0.1-SNAPSHOT/maven-metadata.xml from/to knetminer-repo (https://knetminer.org/artifactory/repository/maven-public): Failed to transfer https://knetminer.org/artifactory/repository/maven-public/uk/ac/ebi/jutils/9.0.1-SNAPSHOT/maven-metadata.xml. Error code 500, javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (4063 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .??	DB name="component"
[WARNING] Failure to transfer uk.ac.ebi:jutils:9.0.1-SNAPSHOT/maven-metadata.xml from https://knetminer.org/artifactory/repository/maven-public was cached in the local repository, resolution will not be reattempted until the update interval of knetminer-repo has elapsed or updates are forced. Original error: Could not transfer metadata uk.ac.ebi:jutils:9.0.1-SNAPSHOT/maven-metadata.xml from/to knetminer-repo (https://knetminer.org/artifactory/repository/maven-public): Failed to transfer https://knetminer.org/artifactory/repository/maven-public/uk/ac/ebi/jutils/9.0.1-SNAPSHOT/maven-metadata.xml. Error code 500, javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (4063 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .??	DB name="component"
[WARNING] The POM for uk.ac.ebi:jutils:jar:9.0.1-SNAPSHOT is missing, no dependency information available`

**Comment by marco-brandizi** [comment]
Hi @cbobed, please bear with us. This started on Thursday afternoon, right when everybody was starting their easter break (what a lucky year...). As the message says, it's a problem with our Maven repository manager, it complaints even when downloading stuff, cause it has to store artifacts cached from 3rd-party repositories. We're upgrading its disk space right now, will let you know when ready. I hope by today or tomorrow, if you need it more urgently, write me at name.surname _at_ rothamsted ac _ uk and I can try to tell you what you need to download manually.

**Comment by cbobed** [comment]
Hi, 

no problem at all. I've downloaded the dependencies and built them locally; it was just to notify this. I close it as you are already handling it :)

Thank you very much! 

Best,
